"""
tools.py: the TOOLS the agent can call.

How "tool calling" works
------------------------
Instead of putting everything in the prompt (expensive in tokens), we describe to the LLM
a list of available functions (name + description + parameters). The LLM
then replies either with text, or with "call get_co2_forecast(hours=12)".
The HARNESS runs the Python function and sends the result back to the LLM.

Why Pydantic for the parameters?
- We write the parameters ONCE (one class), and we get:
  1. the JSON schema sent to the LLM (it knows what to provide);
  2. validation of the arguments it sends back (small models often get it
     wrong: wrong type, missing field...). A validation error is
     sent back TO THE LLM as text, so it can correct itself.

Sobriety: we strip the "title" fields from the schema generated by Pydantic.
Useless to the LLM, they add tokens to EVERY call.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any, Callable

from pydantic import BaseModel, ValidationError


def _clean_schema(schema: dict) -> dict:
    """Recursively removes 'title' keys (saves tokens)."""
    if isinstance(schema, dict):
        return {k: _clean_schema(v) for k, v in schema.items() if k != "title"}
    if isinstance(schema, list):
        return [_clean_schema(x) for x in schema]
    return schema


class NoArgs(BaseModel):
    """For a tool with no parameters."""


@dataclass
class Tool:
    name: str
    description: str
    fn: Callable[[BaseModel], Any]
    args_model: type[BaseModel] = NoArgs

    def schema(self) -> dict:
        """Format expected by Ollama (and by the OpenAI API) to describe a tool."""
        return {
            "type": "function",
            "function": {
                "name": self.name,
                "description": self.description,
                "parameters": _clean_schema(self.args_model.model_json_schema()),
            },
        }


class ToolRegistry:
    """An agent's tool catalog."""

    def __init__(self, tools: list[Tool] | None = None):
        self._tools: dict[str, Tool] = {t.name: t for t in (tools or [])}

    def add(self, tool: Tool) -> None:
        self._tools[tool.name] = tool

    def schemas(self) -> list[dict]:
        return [t.schema() for t in self._tools.values()]

    def call(self, name: str, arguments: dict) -> str:
        """
        Runs a tool and ALWAYS returns a string (even on error).
        Harness principle: an error does not stop the agent, it becomes
        information sent back to it.
        """
        tool = self._tools.get(name)
        if tool is None:
            return f"ERROR: unknown tool '{name}'. Available tools: {list(self._tools)}"
        try:
            args = tool.args_model.model_validate(arguments or {})
        except ValidationError as e:
            return f"ERROR: invalid arguments for {name}: {e.errors()[:2]}"
        try:
            result = tool.fn(args)
        except Exception as e:  # send the error back to the LLM rather than crash
            return f"ERROR while running {name}: {e}"
        return result if isinstance(result, str) else json.dumps(result, ensure_ascii=False)
